name: Variables de entorno

on:
  push:
    branches: [ feature/global-env ]
env: 
  GLOBAL_VAR: test

jobs: 
  primer-job:
    name: Un Job
    runs-on: ubuntu-latest
    steps:
      - name: Salida Variable Entono #Output Global Variable
        run: echo ${GLOBAL_VAR} # Linea original ejerciio
  segundo-job:
    name: Otro Job #Another Job
    runs-on: ubuntu-latest
    steps:
      - name: Salida Var Entorno 2Do Job
        run: echo "Salida Variable de Entorno desde el 2Do Job es ${GLOBAL_VAR}."