name: Dependen Jobs
#Los Jons se pueden encadenar en serie mediante la propiedad.needs
#URL: https://github.com/samueljmello/github-actions-exercises/blob/main/06-Dependent-Jobs.md
#Este ejercicio te guiará a través de la creación de un conjunto encadenado de trabajos que dependen unos de otros. 
# Paso 1: Primero crearemos dos trabajos independientes entre sí (corriendo en paralelo).

on:
  push: 
    branches: feature/dependent
jobs:
  first-name:
    name: Primer Job
    runs-on: ubuntu-latest
    steps: 
    - name: Información Job
      env:
        CONTEXT_ITEM: ${{ toJson(job) }} # convierte toda la información del job al formato JSON.
      run: echo "${CONTEXT_ITEM}"